---
- hosts: webservers
  user: root
  gather_facts: true # need ansible_eth0.ipv4.address for index.html template
  tasks:
    - name: Create index.html
      template: src=templates/index.html.j2 dest=/var/www/index.html
