---
- hosts: web-servers
  user: root
  gather_facts: false
  tasks:
  - group: name={{username}} state=present
  - user: name={{username}} group={{username}} shell=/bin/bash generate_ssh_key=yes
  - fetch: src=/home/{{username}}/.ssh/id_rsa.pub dest=var/deployer.pub flat=yes
  - authorized_key: user={{username}}
      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - apt: pkg=nginx state=present
  - action: file path=/etc/nginx/sites-enabled/default state=absent
    notify: restart nginx
  - template: src=templates/todomvc.conf.j2
      dest=/etc/nginx/sites-available/{{app_name}}.conf
  - command: ln -s /etc/nginx/sites-available/{{app_name}}.conf /etc/nginx/sites-enabled/{{app_name}}.conf creates=/etc/nginx/sites-enabled/{{app_name}}.conf
    notify: restart nginx
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted

- hosts: git-server
  user: root
  gather_facts: false
  tasks:
  - authorized_key: user=git key="{{ lookup('file', 'var/deployer.pub') }}"

- hosts: web-servers
  user: root
  tasks:
  - shell: "mkdir {{item}}; chown {{username}}:{{username}} {{item}};
      chmod 0755 {{item}}"
    with_items:
    - /home/deployer/todomvc-sinatra
    - /home/deployer/todomvc-sinatra/shared
    - /home/deployer/todomvc-sinatra/shared/pids
    - /home/deployer/todomvc-sinatra/shared/log
    - /home/deployer/todomvc-sinatra/releases
  - apt: pkg=libpq-dev state=present

# gotta pull from git until I get authorized_keys setup to push from jenkins
- hosts: jenkins-server
  user: git
  tags: last
  tasks:
  - command: "git fetch jenkins master:master
      chdir=/home/git/todomvc-sinatra-builds"

- hosts: web-servers
  user: "{{username}}"
  tags: last
  tasks:
  - command: "git clone ssh://git@107.170.23.62/home/git/todomvc-sinatra-builds /home/deployer/todomvc-sinatra/current creates=/home/deployer/todomvc-sinatra/current"
  - command: "git pull origin master chdir=/home/deployer/todomvc-sinatra/current"
  - local_action: "shell bundle exec ruby -r securerandom -e 'puts SecureRandom.hex(64)' > var/session_secret creates=var/session_secret"
  - lineinfile: dest=/home/deployer/todomvc-sinatra/current/.env.production
      regexp="^SESSION_SECRET="
      line="SESSION_SECRET={{lookup('file', 'var/session_secret')}}"
  - command: "bundle install --deployment --path /home/deployer/todomvc-sinatra/shared/vendor_bundle chdir=/home/deployer/todomvc-sinatra/current"
  - shell: "RACK_ENV=production bundle exec rake db:migrate chdir=/home/deployer/todomvc-sinatra/current"
