---
- hosts:
  #- webservers
  - jenkinsserver
  user: root
  gather_facts: false
  tasks:
  - apt: pkg={{item}} state=present
    with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - exuberant-ctags
    - git-core
    - libreadline6
    - libreadline6-dev
    - libreadline-dev
    - libsqlite3-0
    - libsqlite3-dev
    - libssl-dev
    - libyaml-dev
    - libc6-dev
    - libncurses5-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - openssl
    - sqlite3
    - subversion
    - zlib1g
    - zlib1g-dev
    - ruby1.9.1
    - ruby1.9.1-dev
    - ri1.9.1
    - libruby1.9.1

  - gem: name=bundler state=present user_install=no
