---
- hosts: webservers
  user: root
  tasks:
  - name: Install ntp 
    apt: pkg=ntp state=present
    tags: ntp
  - name: Configure ntp file
    template: src=templates/ntp.conf.j2 dest=/etc/ntp.conf
    tags: ntp
    notify: restart ntp
  - name: Start the ntp service
    service: name=ntp state=started enabled=true
    tags: ntp
  handlers:
  - name: restart ntp
    service: name=ntpd state=restarted
  - name: restart iptables
    service: name=iptables state=restarted
