---
- hosts: all
  user: root
  gather_facts: true # need to know the hostname
  tasks:
  - lineinfile: "dest=/etc/zabbix/zabbix_agentd.conf regexp='^Server='
    line='Server={{zabbix_server_ip}}'"
    notify: restart zabbix-agent
  - lineinfile: "dest=/etc/zabbix/zabbix_agentd.conf regexp='^ServerActive='
    line='ServerActive={{zabbix_server_ip}}'"
    notify: restart zabbix-agent
  - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="^Hostname="
      line="Hostname={{ansible_hostname}}"
    notify: restart zabbix-agent
  - template: src=templates/userparameter_aptcheck.conf
              dest=/etc/zabbix/zabbix_agentd.d/userparameter_aptcheck.conf
    notify: restart zabbix-agent
  handlers:
  - name: restart zabbix-agent
    service: name=zabbix-agent state=restarted
