---
# adapted from https://www.zabbix.com/documentation/2.2/manual/installation/install_from_packages
- hosts: zabbix-server
  user: root
  gather_facts: false
  tasks:
  - get_url: "dest=~/zabbix-release_2.2-1+precise_all.deb
      url=http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+precise_all.deb"
  - command: "dpkg -i zabbix-release_2.2-1+precise_all.deb"
  - command: "rm zabbix-release_2.2-1+precise_all.deb"
  - command: apt-get update
  - apt: pkg={{item}} state=present
    with_items:
    - zabbix-server-mysql
    - zabbix-frontend-php
    - heirloom-mailx
    - sendmail
  - lineinfile: dest=/etc/apache2/conf.d/zabbix
      regexp="^#? ?php_value date.timezone"
      line="php_value date.timezone {{timezone}}"
  - template: src=templates/zabbix.conf.php
              dest=/etc/zabbix/web/zabbix.conf.php
  - command: service apache2 restart
